[profile.default]
src = "src"
out = "out"
libs = ["lib"]



# Enable optimizer and set runs
optimizer = true
optimizer_runs = 200

remappings = [
    "thirdweb-dynamic=lib/dynamic-contracts", 
    "@thirdweb-dev/contracts=lib/contracts/contracts", 
    "openzeppelin-contract=lib/openzeppelin-contracts/contracts",
    "chainlink-contract=lib/contracts/lib/chainlink"
    ]

# [invariant]
# runs = 500
# depth = 500
# fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
